
SELECT*
FROM UNIVERSITY;

--Trend analysis for the dataset
SELECT DISTINCT YEAR
FROM UNIVERSITY
ORDER BY YEAR ASC;

---INTERNALIZATION ANALYSIS

--Analyze the trends in the international outlook of COUNTRIES over the years
SELECT COUNTRY,YEAR,AVG(INTERNATIONAL_OUTLOOK) AS AVG_INTERNATIONAL_OUTLOOK
FROM UNIVERSITY
GROUP BY COUNTRY,YEAR
ORDER BY YEAR,AVG_INTERNATIONAL_OUTLOOK DESC;

---Identify countries with the highest concentration of international students.
SELECT COUNTRY,YEAR,AVG(INTERNATIONAL_STUDENT) AS AVG_IS
FROM UNIVERSITY
GROUP BY COUNTRY,YEAR
ORDER BY YEAR,AVG_IS DESC;

--Universities with the highest concentration of international students in 2023.
SELECT NAME,INTERNATIONAL_STUDENT
FROM UNIVERSITY
WHERE YEAR=2023
ORDER BY INTERNATIONAL_STUDENT DESC;

--IMPACT OF RESEARCH ENVIRONMENT

--Countries with average research enivronment greater than 20
SELECT COUNTRY,YEAR,AVG(RESEARCH_ENVIRONMENT) AS AVG_RE
FROM UNIVERSITY
GROUP BY COUNTRY,YEAR
HAVING AVG(RESEARCH_ENVIRONMENT)>20
ORDER BY YEAR ASC,AVG_RE DESC;

--Universities that have an industry impact score above the average.
SELECT NAME,INDUSTRY_IMPACT,YEAR
FROM UNIVERSITY
WHERE INDUSTRY_IMPACT >(SELECT AVG(INDUSTRY_IMPACT)
                        FROM UNIVERSITY
                       );
--STUDENT ANALYSIS

--Student Population to Teaching quality
SELECT COUNTRY,YEAR,AVG(STUDENT_POPULATION)/AVG(TEACHING) AS AVG_STD_TO_TEA
FROM UNIVERSITY
GROUP BY COUNTRY,YEAR
ORDER BY YEAR ASC;

--Relationship between student-to-staff ratio and teaching quality.
SELECT COUNTRY,YEAR,AVG(STUDENTS_TO_STAFF_RATIO)/AVG(TEACHING) AS AVG_STDS_TO_TEA
FROM UNIVERSITY
GROUP BY COUNTRY,YEAR
ORDER BY YEAR ASC;

--Top 10 University with highest student population over the years
SELECT TOP 10 NAME,STUDENT_POPULATION,YEAR
FROM UNIVERSITY
WHERE YEAR IN(2016,2017)
ORDER BY YEAR ASC,STUDENT_POPULATION DESC;

---UNIVERSITY ANALYSIS

--Rank 1 Universities over the years
SELECT NAME,YEAR
FROM UNIVERSITY
WHERE RANK=1
GROUP BY NAME,YEAR
ORDER BY YEAR;

--TOP 20 University ranking over the years
SELECT RANK,NAME,YEAR,COUNTRY
FROM UNIVERSITY
WHERE RANK BETWEEN 1 AND 20
GROUP BY RANK,NAME,YEAR,COUNTRY
ORDER BY YEAR;

--Bottom Ranked University over the years
SELECT NAME,SUB.RANK,SUB.YEAR
FROM UNIVERSITY AS UTY
JOIN (SELECT YEAR,MAX(RANK) AS RANK
      FROM UNIVERSITY
	  GROUP BY YEAR) AS SUB
ON UTY.RANK=SUB.RANK
ORDER BY SUB.YEAR;
 
--COUNTRYWISE ANALYSIS

--Numbers of UNIVERSITY present in top 30 for each country over years
SELECT COUNTRY,YEAR,COUNT(*) AS UNI_COUNT
FROM UNIVERSITY
WHERE RANK <=30
GROUP BY COUNTRY,YEAR
ORDER BY YEAR,UNI_COUNT;

--Average Student population in each country over the years
SELECT COUNTRY,YEAR,AVG(STUDENT_POPULATION) AS AVG_STD_POPULATION
FROM UNIVERSITY
GROUP BY COUNTRY,YEAR
ORDER BY YEAR;

--Countries' universities performance in terms of Research Quality, internationalization, and overall ranking.
SELECT COUNTRY,YEAR,AVG(RESEARCH_QUALITY) AS AVG_RQ, AVG(INTERNATIONAL_OUTLOOK) AS AVG_IO,AVG(OVERALL_SCORE) AS AVG_OS
FROM UNIVERSITY
WHERE RANK<=30
GROUP BY COUNTRY,YEAR
ORDER BY YEAR,AVG_RQ;

--SPECIFIC COUNTRIES ANALYISIS (UNITED STATES, UNITED KINGDOM,NIGERIA)

--Universites with the highest student population in the countries

SELECT TOP 10 NAME,STUDENT_POPULATION,YEAR
FROM UNIVERSITY
WHERE COUNTRY ='UNITED KINGDOM'
ORDER BY STUDENT_POPULATION DESC;

SELECT TOP 10 NAME,STUDENT_POPULATION,YEAR
FROM UNIVERSITY
WHERE COUNTRY ='UNITED STATES'
ORDER BY STUDENT_POPULATION DESC;

SELECT NAME,YEAR,STUDENT_POPULATION
FROM UNIVERSITY
WHERE COUNTRY ='NIGERIA'
GROUP BY STUDENT_POPULATION,NAME,YEAR
ORDER BY STUDENT_POPULATION DESC;